anicheck/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('signup/', views.signup, name='signup'),
]

blog/urls.py
"""This module use for specify the path of the web application."""

from django.urls import path

import blog.views.search_view
import blog.views.review_view
import blog.views.about_us_view
import blog.views.user_view
import blog.views.mylist_view

app_name = 'blog'

urlpatterns = [

    path('', blog.views.search_view.index, name='index'),
    path('kitsu/<str:title>/', blog.views.search_view.kitsu, name='kitsu'),
    path('kitsu/search', blog.views.search_view.kitsu_search, name='search'),
    path('reviews/', blog.views.review_view.ReviewsView.as_view(), name='reviews'),
    path('create-review/', blog.views.review_view.CreateReviewView.as_view(success_url="/reviews"), name='create-review'),
    path('contact/', blog.views.about_us_view.about_us, name='contact'),
    path('profile/<int:pk>', blog.views.user_view.ProfilePageView.as_view(), name='profile'),
    path('profile/edit', blog.views.user_view.update_user, name='profile-edit'),
    path('profile/<int:pk>/mylist/', blog.views.mylist_view.MyListView.as_view(), name='mylist'),
    path('profile/<int:pk>/mylist/add/<str:title>', blog.views.search_view.add_mylist, name='add-mylist'),
    path('profile/<int:pk>/mylist/remove/<str:title>', blog.views.search_view.remove_mylist, name='remove-mylist'),
]

blog/models.py
import asyncio
import requests
import kitsu

client = kitsu.Client()


async def anime_search(query):
    demo = {}
    entries = await client.search('anime', query, limit=2)

    if not entries:
        demo += f'No entries found for "{query}"'
        return demo

    for i, anime in enumerate(entries, 1):
        s_links = {}
        streaming_links = await client.fetch_anime_streaming_links(anime)
        if streaming_links:
            for link in streaming_links:
                s_links[link.title] = link.url

        # print(anime.title+"l")

        # url = 
        anime_title = anime.title

        use_url = f"https://kitsu.io/api/edge/anime?filter[text]={anime_title}"

        response = requests.get(use_url)
        # 
        # l = response.json()['data']
        # poster_image_link = ""
        # for info in l:
        # 'titles']['titles'][        #     if "DragonBall" in info['attributes']['titles']['en']:
        #         poster_image_link = info['attributes']['posterImage']['original']
        # break

        demo[anime.title] = {
            "sub-type": anime.subtype,
            "status": anime.status,
            "synopsis": anime.synopsis,
            "episode": anime.episode_count,
            "age-rating": anime.age_rating_guide,
            "popularity": anime.popularity_rank,
            "rating": anime.rating_rank,
            # "start_at" : anime.started_at.strftime('%Y-%m-%d'),
            # "ended_at" : anime.ended_at.strftime('%Y-%m-%d'),
            # "link": s_links,
            # "poster": poster_image_link
        }
    return demo


async def anime_search_title(query):
    entries = await client.search('anime', query)
    results = []
    if not entries:
        print(f'No entries found for "{query}"')
        return

    for i, anime in enumerate(entries, 1):
        anime_title = anime.title.replace('/', '-')
        results.append(anime_title)

    print(results)
    print(query)

    # user_choice = int(input("Choose anime from list 1,2,3,4,5: "))
    # user_choice -= 1
    # anime_name = results[user_choice]
    # print(anime_name)
    return results
# 
# anime = 'Dragon Ball'
# 
# loop = asyncio.get_event_loop()
# loop.create_task(anime_search(str(anime)))
# # loop.run_until_complete(anime_search(str(anime)))
# data = loop.run_until_complete(asyncio.gather(anime_search(anime)))[0]
# # data = loop.run_until_complete(asyncio.as_completed(anime_search(anime)))
# print(data['Dragon Ball'])
# anime_search('Pokemon Introductory Recap')
# 
# # for k,v in data.items():
#     print(k,v)

blog/models/blog.py
"""Model for Blog."""
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class Review(models.Model):
    """Model for Review."""
    title = models.CharField(max_length=50, blank=False)
    body = models.TextField(max_length=500, blank=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, related_name="reviews", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Reviews"

    def __str__(self):
        return str(self.title)

    def is_published(self):
        now = timezone.now()
        if now >= self.pub_date:
            return True
        return False

blog/models/models_search.py
import asyncio
import requests
import kitsu

client = kitsu.Client()


async def anime_search(query):
    demo = {}
    entries = await client.search('anime', query, limit=2)

    if not entries:
        demo += f'No entries found for "{query}"'
        return demo

    for i, anime in enumerate(entries, 1):
        s_links = {}
        streaming_links = await client.fetch_anime_streaming_links(anime)
        if streaming_links:
            for link in streaming_links:
                s_links[link.title] = link.url
        anime_title = anime.title

        use_url = f"https://kitsu.io/api/edge/anime?filter[text]={anime_title}"

        response = requests.get(use_url)
        json_data = response.json()['data']
        poster_image_link = ""
        for info in json_data:
            poster_image_link = info['attributes']['posterImage']['original']
 
        demo[anime.title] = {
            "names": anime.title,
            "sub-type": anime.subtype,
            "status": anime.status,
            "synopsis": anime.synopsis,
            "episode": anime.episode_count,
            "age-rating": anime.age_rating_guide,
            "popularity": anime.popularity_rank,
            "rating": anime.rating_rank,
            "images": anime.poster_image_url,
        }
    return demo


async def anime_search_title(query):
    entries = await client.search('anime', query)
    results = []
    if not entries:
        print(f'No entries found for "{query}"')
        return

    for i, anime in enumerate(entries, 1):
        anime_title = anime.title.replace('/', '-')
        results.append(anime_title)
    return results

blog/models/mylist.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import json


class MyList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mylist = models.TextField(blank=True)

    def set_mylist(self, new_mylist):
        self.mylist = json.dumps(list(new_mylist))

    def get_mylist(self):
        return set(json.loads(self.mylist))

    def add_mylist(self, title):
        title = title.replace('/', '-')
        temp = self.get_mylist()
        temp.add(title)
        self.set_mylist(temp)

    def remove_mylist(self, title):
        title = title.replace('/', '-')
        temp = self.get_mylist()
        temp.remove(title)
        self.set_mylist(temp)

@receiver(post_save, sender=User)
def mylist_create(sender, instance=None, created=False, **kwargs):
    if created:
        MyList.objects.create(user=instance, mylist='[]')

blog/forms.py
from django import forms

from blog.models.blog import Review
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CharFieldForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['title', 'body']
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Review title'}),
            'body': forms.Textarea(attrs={'class': 'form-control',
                                                       'placeholder': 'Description...'}),
        }

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

blog/views/about_us_view.py
from django.shortcuts import render


def about_us(request):
    return render(request, 'blog/contact.html', )

blog/views/mylist_view.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from blog.models.mylist import MyList
from django.contrib.auth.models import User

class MyListView(ListView):
    model = User
    template_name = 'blog/mylist.html'

    def get_context_data(self, *args, **kwargs):
        locate = get_object_or_404(User, id=self.kwargs['pk'])
        object_list = locate.mylist.get_mylist()

        context = super(MyListView, self).get_context_data(locate=locate, object_list=object_list, **kwargs)
        return context

# def mylist(request):
#     return render(request, 'blog/mylist.html')

blog/views/review_view.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from blog.models.blog import Review

class ReviewsView(ListView):
    model = Review
    template_name = 'blog/reviews.html'
    ordering = ['-pub_date']
    context_object_name = 'reviews'
    paginate_by = 10

class CreateReviewView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'blog/create_review.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeleteReviewView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Review
    success_url = '/'

    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        return False

blog/views/search_view.py
from django.forms import forms
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
import blog.models.models_search
import asyncio
import nest_asyncio
from ..forms import CharFieldForm
nest_asyncio.apply()


def index(request):
    return render(request, 'blog/blog_index.html', )


async def kitsu(request, title):
    if title is None:
        return HttpResponse("กรอกด้วยไอสัส")
    loop = asyncio.get_event_loop()
    loop.create_task(blog.models.models_search.anime_search(title))
    data = loop.run_until_complete(asyncio.gather(blog.models.models_search.anime_search(title)))[0]
    return render(request, 'blog/show_detail.html', context={
        "url": title,
        "title": data[next(iter(data))]['names'],
        "sub_type": data[next(iter(data))]['sub-type'],
        "status": data[next(iter(data))]['status'],
        "synopsis": data[next(iter(data))]['synopsis'],
        "episode": data[next(iter(data))]['episode'],
        "age_rating": data[next(iter(data))]['age-rating'],
        "popularity": data[next(iter(data))]['popularity'],
        "rating": data[next(iter(data))]['rating'],
        "image" : data[next(iter(data))]['images'],
    })


async def kitsu_search(request):
    keyword = request.GET['keyword']
    loop = asyncio.get_event_loop()
    loop.create_task(blog.models.models_search.anime_search_title(keyword))
    data = loop.run_until_complete(asyncio.gather(blog.models.models_search.anime_search_title(keyword)))[0]
    return render(request, 'blog/search.html', context={'title_list': data})


def charfield(request):
    if request.method == 'POST':
        forms = CharFieldForm(request.POST)
    else:
        form = CharFieldForm()
    return render(request, 'blog/charfield.html', {'form': 'form'})

def review_anime(request):
    return render(request, 'blog/review.html')

@login_required
def add_mylist(request, title, pk):
    print(title)
    request.user.mylist.add_mylist(title)
    request.user.mylist.save()
    return redirect('blog:mylist', pk=pk)


@login_required
def remove_mylist(request, title, pk):
    request.user.mylist.remove_mylist(title)
    request.user.mylist.save()
    return redirect('blog:mylist', pk=pk)

blog/views/user_view.py
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.views.generic.list import MultipleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from ..forms import UpdateProfileForm
from django.contrib.auth.decorators import login_required



class ProfilePageView(DetailView, MultipleObjectMixin):
    model = User
    template_name = 'blog/user_profile.html'
    paginate_by = 2

    def get_context_data(self, *args, **kwargs):
        locate = get_object_or_404(User, id=self.kwargs['pk'])
        object_list = self.object.reviews.filter().order_by('-pub_date')

        context = super(ProfilePageView, self).get_context_data(locate=locate, object_list=object_list, **kwargs)
        return context

@login_required
def update_user(request, **kwargs):
    profile_form = UpdateProfileForm(instance=request.user)
    if request.method == 'POST':
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user)

        if profile_form.is_valid():
            profile_form.save()

            return redirect('blog:profile', pk=request.user.id)
    return render(request, 'blog/edit_profile.html', {'profile_form': profile_form})

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<link
  href="https://fonts.googleapis.com/css2?family=Cabin+Sketch:wght@700&family=Codystar&family=Comfortaa&family=Cutive+Mono&family=Dokdo&family=Finger+Paint&family=Indie+Flower&family=Lexend+Mega&family=Londrina+Outline&family=Luckiest+Guy&family=Press+Start+2P&family=Reenie+Beanie&family=Short+Stack&family=Yomogi&display=swap"
  rel="stylesheet" />

<body>
  <div class="navbar">
    <a href="{% url 'blog:index' %}"><i class="fa fa-fw fa-home"></i></a>
    <a href="{% url 'blog:contact' %}"> About us</a>
    <a href="{% url 'blog:reviews' %}"> Reviews</a>

    {% if user.is_authenticated %}
    <div class="subnav">
      <button class="subnavbtn">User <i class="fa fa-caret-down"></i></button>
      <div class="subnav-content">
        <a href="{% url 'blog:profile' pk=user.pk %}">Profile</a>
        <a href="{% url 'blog:profile-edit' %}"> Edit Profile</a>
        <a href="{% url 'blog:create-review' %}"> Create Reviews</a>
        <a href="{% url 'blog:mylist' pk=user.pk %}">MyList</a>
      </div>
    </div>

    {% endif %}
    <div>
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}"><i class="fa fa-fw fa-unlock"></i> Logout</a>
      {% else %}
      <a href="{% url 'login' %}"><i class="fa fa-fw fa-lock"></i> Login</a>
      {% endif %}
    </div>

    <div class="search-container">
      <form action="{% url 'blog:search' %}" method="get">
        <input type="text" name="keyword" placeholder="Search.." />
      </form>
    </div>
  </div>

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      /* Hide scrollbar for Chrome, Safari and Opera */
      body::-webkit-scrollbar {
        display: none;
      }

      /* Hide scrollbar for IE, Edge and Firefox */
      body {
        -ms-overflow-style: none;
        scrollbar-width: none;
      }

      a {
        font-family: "Raleway", sans-serif;
      }

      .navbar {
        overflow: hidden;
        background-color: #0b1c22;
      }

      .navbar a {
        float: left;
        font-size: 16px;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }

      .subnav {
        float: left;
        overflow: hidden;
      }

      .subnav .subnavbtn {
        font-size: 16px;
        border: none;
        outline: none;
        color: white;
        padding: 14px 16px;
        background-color: inherit;
        font-family: inherit;
        margin: 0;
      }

      .navbar a:hover,
      .subnav:hover .subnavbtn {
        background-color: #2b2b2b;
        color: white;
      }

      .subnav-content {
        display: none;
        position: absolute;
        left: 0;
        background-color: #2b2b2b;
        width: 100%;
        z-index: 1;
        color: white;
      }

      .subnav-content a {
        float: left;
        color: white;
        text-decoration: none;
      }

      .subnav-content a:hover {
        background-color: #fffd5e;
        color: black;
      }

      .subnav:hover .subnav-content {
        display: block;
      }

      .navbar input[type="text"] {
        float: right;
        padding: 6px;
        border: none;
        margin-top: 8px;
        margin-right: 16px;
        font-size: 17px;
        font-family: "Raleway", sans-serif;
      }

      .search-container input[type="text"] {
        width: 130px;
        box-sizing: border-box;
        border: 2px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
        background-color: white;
        background-image: url("https://www.maxpixel.net/static/photo/1x/Lense-Pictogram-Loupe-Gray-Hint-Magnifying-Glass-308581.png");
        background-size: 18px;
        background-position: 10px 8px;
        background-repeat: no-repeat;
        padding: 8px 20px 8px 40px;
        -webkit-transition: width 0.4s ease-in-out;
        transition: width 0.4s ease-in-out;
        margin: 5px 20px 0px 0px;
      }

      .search-container input[type="text"]:focus {
        width: 40%;
      }

      footer {
        margin: auto; 
        padding: 0px 0px 20px 0px; 
        width: 100%; 
        height:120px;
        background-color: #0b1c22; 
        background-size:100% 100%;
      }

      .anicheck-footer {
        font-size: 16px;
        font-weight: bold;
        color: white;
        text-align: center;
        padding-top: 50px;
        padding-bottom: 10px;
      }

      .anicheck-link a{
        font-size: 14px;
        color: white;
      }

      .anicheck-link {
        text-align: center;
      }

    </style>
  </head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'blog/transit_image.css' %}" />

  {% block content %}{% endblock %}
</body>

</html>

blog/templates/blog/charfield.html
{% block body %}
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <table>
            {{ form.media }}
            {{ form.as_p }}
            <button type="submit">OK</button>
        </table>
    </form>
    {% if form.is_valid %}
        <br>
        Memo: {{ form.memo.value }} <br>
    {% endif %}
{% endblock %}

blog/templates/blog/create_review.html
{% extends "blog/base.html" %} {% block content %}
<!DOCTYPE html>
<html>

<head>
    <title>Create Review</title>

<body>
    <h2>Reviews Form</h2>
    <div class="create-container">
        <div class="col-md-8">
            <div class="card mb-4 mt-4">
                <div class="card-header"></div>
                <div class="card-body">
                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %} {{ form.media }} <br />
                        {{ form.as_p }} <br /><br />
                        <input type="submit" class="btn-primary">
                        <a href="{% url 'blog:reviews' %}"> </a>
                        </input>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <style>

        body {
            background-image: url("https://images8.alphacoders.com/118/thumb-1920-1182938.png");
            background-size: cover;
        }

        h2 {
            margin-top: 60px;
            margin-left: 40px;
            font-family: 'Raleway', sans-serif;
        }

        .create-container [type="text"],
        select,
        textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-top: 6px;
            margin-bottom: 16px;
            resize: vertical;
            font-family: 'Raleway', sans-serif;
            font-size: 16px;
        }

        .create-container [type="submit"] {
            background-color: #FF708C;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-family: 'Raleway', sans-serif;
            font-size: 14px;
        }

        .create-container [type="submit"]:hover {
            background-color: #04aa6d;
            font-family: 'Raleway', sans-serif;
        }

        .create-container {
            color: black;
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
            margin: 20px;
            font-family: 'Raleway', sans-serif;
            opacity: 0.5;
            background-size: 80%;
        }

        .create-container:hover,
        label:hover{
            border-radius: 5px;
            opacity: 1;
            padding: 20px;
            margin: 20px;
            font-family: 'Raleway', sans-serif;
            color: black;
        }

        label {
            font-size: 16px;
            font-family: 'Raleway', sans-serif;
        }
    </style>
</body>
</head>

</html>

{% endblock %}

blog/templates/blog/mylist.html
{% extends "blog/base.html" %} {% block content %}

<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My List</title>
    <style>
      body {
        background-image: url("https://images7.alphacoders.com/113/thumb-1920-1132478.png");
        height: 100vh;
        background-repeat: no-repeat;
        background-size: cover;
      }

      .alert {
        padding: 20px;
        background-color: #ffbd00;
        color: white;
        font-family: "Raleway", sans-serif;
      }

      .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
      }

      .closebtn:hover {
        color: black;
      }

      h2 {
        margin-top: 60px;
        margin-left: 20px;
        font-family: "Raleway", sans-serif;
      }

      body {
        font-family: "Raleway", sans-serif;
      }

      .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.4);
        border-radius: 25px;
      }

      .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 30px;
        border: 1px solid #888;
        width: 80%;
        font-family: "Raleway", sans-serif;
        border-radius: 10px;
      }

      .close {
        color: #aaaaaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
      }

      .close:hover,
      .close:focus {
        color: #000;
        text-decoration: none;
        cursor: pointer;
      }

      .container {
        height: 50vh;
        position: relative;
      }

      .center {
        margin: 0;
        position: absolute;
        top: 50%;
        left: 50%;
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
      }

      .list-button button {
        font-size: 24px;
        font-weight: bold;
        padding: 20px 40px 30px 40px;
        background-color: transparent;
        background-repeat: no-repeat;
        border: none;
        cursor: pointer;
        overflow: hidden;
        outline: none;
      }

      .list-button button:hover {
        color: white;
        opacity: 0.8;
      }

      .glow {
        color: #f45d06;
        text-align: center;
        animation: glow 1s ease-in-out infinite alternate;
        margin-top: 500px;
        margin-left: 50px;
      }

      @keyframes glow {
        from {
          text-shadow: 0 0 0px #fff, 0 0 5px #fff, 0 0 10px #fee682,
            0 0 15px #fee682, 0 0 20px #fee682, 0 0 25px #fee682,
            0 0 30px #fee682;
        }

        to {
          text-shadow: 0 0 10px #fff, 0 0 15px #fee682, 0 0 20px #fee682,
            0 0 25px #fee682, 0 0 30px #fee682, 0 0 35px #fee682,
            0 0 40px #fee682;
        }
      }

      p {
        text-align: center;
        color: white;
        font-size: 14px;
        text-decoration: under;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
        margin-left: 50px;
      }

      .title {
        font-size: 20px;
        color: #0b1c22;
      }

      .title:hover {
        color: #ff3c00;
      }

      .remove {
        font-size: 14px;
        color: salmon;
      }

      .remove:hover {
        color: red;
      }
    </style>
  </head>

  <body>
    {% if not object_list %}
    <div class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';"
        >&times;</span
      >
      <strong>Info!</strong> There aren't any favorite anime yet, so go find
      some and add it!!!
    </div>

    <div class="container">
      <div class="center">
        <div class="list-button">
          <button id="myBtn">
            <h1 class="glow">{{ user.username }}'s List</h1>
          </button>
          <p>Click For Your List</p>
        </div>
      </div>
    </div>
    {% endif %} {% if object_list %}
    <div class="container">
      <div class="center">
        <div class="list-button">
          <button id="myBtn">
            <h1 class="glow">{{ user.username }}'s Favorite List</h1>
          </button>
          <p>Click For Your List</p>
        </div>
      </div>
    </div>

    <div id="myModal" class="modal">
      <div class="modal-content">
        <span class="close">&times;</span>

        <table>
          {% for title in object_list %}
          <tr>
            <td>
              <a href="{% url 'blog:kitsu' title=title %}">
                <h1 class="title">{{ title }}</h1>
              </a>
            </td>
            <td>
              <button class="remove-btn">
                <a href="{% url 'blog:remove-mylist' title=title pk=user.pk %}">
                  <h1 class="remove">[remove]</h1>
                </a>
              </button>
            </td>
          </tr>
          {% endfor %}
        </table>
        {% endif %}
      </div>
    </div>

    <script>

      var modal = document.getElementById("myModal");
      var btn = document.getElementById("myBtn");
      var span = document.getElementsByClassName("close")[0];

      btn.onclick = function () {
        modal.style.display = "block";
      };

      span.onclick = function () {
        modal.style.display = "none";
      };

      window.onclick = function (event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      };
    </script>
  </body>
</html>

{% endblock %}

blog/templates/blog/search.html
{% extends "blog/base.html" %}
{% block content %}

<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anime List</title>
    <style>

        body {
            background: hsla(141, 81%, 87%, 1);
            background: linear-gradient(90deg, hsla(141, 81%, 87%, 1) 0%, hsla(41, 88%, 75%, 1) 50%, hsla(358, 82%, 71%, 1) 100%);
            background: -moz-linear-gradient(90deg, hsla(141, 81%, 87%, 1) 0%, hsla(41, 88%, 75%, 1) 50%, hsla(358, 82%, 71%, 1) 100%);
            background: -webkit-linear-gradient(90deg, hsla(141, 81%, 87%, 1) 0%, hsla(41, 88%, 75%, 1) 50%, hsla(358, 82%, 71%, 1) 100%);
            filter: progid: DXImageTransform.Microsoft.gradient( startColorstr="#C5F9D7", endColorstr="#F7D486", GradientType=1 );
        }

        * {
            box-sizing: border-box;
        }

        .zoom {
            transition: transform .2s;
            width: 100px;
            height: 50px;
            margin-right: auto;
            margin-left: 100px;
            margin-top: 50px;
            margin-bottom: 20px;
        }

        .zoom:hover {
            -ms-transform: scale(1.5);
            /* IE 9 */
            -webkit-transform: scale(1.5);
            /* Safari 3-8 */
            transform: scale(1.5);
        }

        h1 {
            font-size: 20px;
            clear: both;
            display: inline-block;
            overflow: hidden;
            white-space: nowrap;
            text-align: center;
            color: #0b1c22;
        }
        
        h1:hover {
            color: #FA1E0E;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #0b1c22;
        }

        th,
        td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f25e;
        }

        .alert {
            padding: 20px;
            background-color: #FA1E0E;
            color: white;
            font-family: "Raleway", sans-serif;
        }

        .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }

        .closebtn:hover {
            color: black;
        }
    </style>
</head>

<body>
    <table>
        {% if title_list %}
        {% for title in title_list %}
        <tr>
            <td><a href="{% url 'blog:kitsu' title=title %}">
                    <div class="zoom">
                        <h1>{{ title }}</h1>
                    </div>
            </td>
            </a>
        </tr>
        {% endfor %}
        {% else %}
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            <strong>Error !</strong> No anime matches your search, Please try again.
        </div>
        {% endif %}
    </table>

</body>

</html>
{% endblock %}